# 7. Customer Segmentation (KMeans)

In [11]:
import pandas as pd
model_df = pd.read_csv("../data/processed/model_df.csv")

In [13]:
seg_cols = [
    'total_trips',
    'avg_fare',
    'total_spend',
    'days_since_last_trip',
    'total_sessions',
    'avg_time_on_app'
]

# Fill missing values with 0
model_df[seg_cols] = model_df[seg_cols].fillna(0)

In [14]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

segmentation_features = model_df[
    ['total_trips','avg_fare','total_spend',
     'days_since_last_trip','total_sessions','avg_time_on_app']
]

scaler_seg = StandardScaler()
X_scaled = scaler_seg.fit_transform(segmentation_features)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
model_df['segment'] = kmeans.fit_predict(X_scaled)

model_df['segment'].value_counts()

segment
0    4916
1    4437
2     647
Name: count, dtype: int64

In [15]:
segment_profile = model_df.groupby('segment')[[
    'total_trips','avg_fare','total_spend',
    'days_since_last_trip','total_sessions',
    'avg_time_on_app','conversion_rate'
]].mean().round(2)

segment_profile

,total_trips,avg_fare,total_spend,days_since_last_trip,total_sessions,avg_time_on_app,conversion_rate
segment,,,,,,,
0,16.79,15.05,251.75,22.41,5.02,74.26,0.15
1,23.62,15.78,371.44,13.54,5.04,77.75,0.15
2,19.56,15.39,300.72,17.72,4.54,408.82,0.18

In [17]:
segment_name_map = {
    0: "Regular commuters (High value)",
    1: "Engaged Value Seekers", 
    2: "Occasional/At-Risk Users"
}
model_df['segment_name'] = model_df['segment'].map(segment_name_map)
model_df[['segment', 'segment_name']].head()

   segment                    segment_name
0        1           Engaged Value Seekers
1        0  Regular commuters (High value)
2        1           Engaged Value Seekers
3        0  Regular commuters (High value)
4        0  Regular commuters (High value)

In [18]:
segment_profile

,total_trips,avg_fare,total_spend,days_since_last_trip,total_sessions,avg_time_on_app,conversion_rate
segment,,,,,,,
0,16.79,15.05,251.75,22.41,5.02,74.26,0.15
1,23.62,15.78,371.44,13.54,5.04,77.75,0.15
2,19.56,15.39,300.72,17.72,4.54,408.82,0.18

In [19]:
model_df.to_csv("../data/processed/model_df_segmented.csv", index=False)
print("Saved segmented dataset")

Saved segmented dataset

# Business Insights
## Segment 0 - Regular commuters 
  Highest trips and spend 
  Most recently active 
  Core revenue segment 
  Low churn risk 
### Recommended Action
  Loyalty rewards, premium memberships, referral bonuses
## Segment 1 - Engaged value seekers 
  High app engagement 
  Moderate trips and spend 
  Likely price sensitive 
### Recommended Action 
  Targeted discounts, personalised promotions, push notifications during peak hours 
## Segment 2 - Occasional/At-risk users 
  Lowest trips and spend 
  Highest inactivity 
  Highest churn risk 
### Recommended Action
  Win-back campaigns, limited-time offers, email re-engagement

In [ ]:
model_df.to_csv("../data/processed/model_df_segmented.csv", index=False)